----
title: "EDE Group Project"
author: "Gaby Czarniak, Mara Michel, Sam Sedar"
date: "2023-11-14"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(here); here()
library(rvest)
library(cowplot)
library(agricolae)
library(dplyr)
library(tidyverse)
library(lubridate)
library(trend)
library(zoo) 
library(Kendall)
library(tseries)
library(sf)
library(leaflet)
library(tseries)
library(mapview); mapviewOptions(fgb = FALSE)

knitr::opts_chunk$set (warning = FALSE, echo = FALSE)

getwd()
```



```{r Data Load}

#Loading Data into Raw Data folder

plant <- read.csv(here('Data/Raw/PLNT21.csv'),
                  stringsAsFactors = FALSE, skip = 1, 
                  colClasses = c('FIPSST' = 'character', 
                                 'FIPSCNTY' = 'character',
                                 'ORISPL' = 'character'))

gen <- read.csv(here('Data/Raw/GEN21.csv'), 
                stringsAsFactors = FALSE, skip = 1, 
                  colClasses = c('ORISPL' = 'character'))

gen20 <- read.csv(here('Data/Raw/GEN20.csv'),                 
                  stringsAsFactors = FALSE, skip = 1, 
                  colClasses = c('ORISPL' = 'character'))

income <- read.csv(here('Data/Raw/PovertyEstimates.csv'), 
                  stringsAsFactors = TRUE, skip = 4)

unemployment <- read.csv(here('Data/Raw/Unemployment.csv'), 
                  stringsAsFactors = TRUE, skip = 4)

SVI <-read.csv(here('Data/Raw/SVI_NorthCarolina_county.csv'),
                  stringsAsFactors = TRUE)
  
```


```{r}
######  DATA WRANGLING - BASELINE  ######

#EGRID DATA

#Selecting columns of interest from plant data
plant_select <- plant %>%
  select(PSTATABB, ORISPL, FIPSST, FIPSCNTY, PLFUELCT, NAMEPCAP,
         PLNGENAN,PLSO2RTA, PLCO2RTA, PLCH4RTA, PLN2ORTA, PLCO2AN, PLN2OAN,PLNOXAN,
         PLSO2AN,PLCH4AN, CNTYNAME, LAT,
         LON, COALFLAG) %>%
  filter(PSTATABB == "NC") %>%
  unite(FIPS_Code, FIPSST, FIPSCNTY, sep = "")

plant_select$PLNGENAN <- as.numeric(plant_select$PLNGENAN)
plant_select$PLCO2RTA <- as.numeric(plant_select$PLCO2RTA)
plant_select$PLCO2AN <- as.numeric(plant_select$PLCO2AN)
plant_select$NAMEPCAP <- as.numeric(plant_select$NAMEPCAP)


#Combining Generator and Plant df based on ORISPL
plant_gen <- gen %>%
  inner_join(plant_select, by = 'ORISPL', 
             suffix = c("_gen", "_plant"))

plant_gen$CFACT <- as.numeric(plant_gen$CFACT)
plant_gen$GENNTOZ <- as.numeric(plant_gen$GENNTOZ)
plant_gen$NAMEPCAP_gen <- as.numeric(plant_gen$NAMEPCAP_gen)
plant_gen$GENNTAN <- as.numeric(plant_gen$GENNTAN)

#Removing duplicate state abbreviation column
plant_gen_data <- plant_gen[, -which(names(plant_gen) == "PSTATABB_plant")]


#UNEMPLOYMENT DATA

#Selecting columns of interest: unemployment rates: 2002-2022

ue <- unemployment %>%
  select(FIPS_Code,	Unemployment_rate_2000,	Unemployment_rate_2001,	Unemployment_rate_2002,	Unemployment_rate_2003,	Unemployment_rate_2004,	Unemployment_rate_2005,	Unemployment_rate_2006,	Unemployment_rate_2007,	Unemployment_rate_2008,	Unemployment_rate_2009,	Unemployment_rate_2010,	Unemployment_rate_2011,	Unemployment_rate_2012,	Unemployment_rate_2013,	Unemployment_rate_2014,	Unemployment_rate_2015,	Unemployment_rate_2016,	Unemployment_rate_2017,	Unemployment_rate_2018,	Unemployment_rate_2019,	Unemployment_rate_2020,	Unemployment_rate_2021,	Unemployment_rate_2022)

#Merging with eGrid
ue_egrid <- merge(plant_gen_data, ue, by = "FIPS_Code")


#INCOME DATA

#Selecting columns of interest: 
inc <- income %>%
  select(FIPS_Code, PCTPOVALL_2021, MEDHHINC_2021)

#Merging
processed_data <- merge(ue_egrid, inc, by = "FIPS_Code")

colnames(processed_data)


```

```{r - Exploration}

########### DATA EXPLORATION - BASELINE ###########

summary(processed_data)

#NC Breakdown of Fuel by Category
fuel_summarized <- processed_data %>%
  group_by(PLFUELCT) %>%
  summarise(total_generation = sum(PLNGENAN, na.rm = TRUE))
print(fuel_summarized)

#In percentages
fuel_summarized$percentage <- fuel_summarized$total_generation / sum(fuel_summarized$total_generation) * 100

#Pie chart with percent makeup of fuel in  NC
pie_chart_percentage <- ggplot(fuel_summarized, aes(x = factor(1), fill = PLFUELCT, y = percentage)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar(theta = "y") +
  labs(title = "North Carolina Primary Fuel (% of Total Annual Generation)",
       fill = "Primary Fuel Type",
       y = "Percentage of Total Generation (%)", x = NULL)
print(pie_chart_percentage)

#Relationship between income and fuel type
processed_data$MEDHHINC_2021 <- as.numeric(processed_data$MEDHHINC_2021)

#Scatter visualization
scatter_income_generation <- ggplot(processed_data, aes(x = MEDHHINC_2021, y = PLNGENAN, color = PLFUELCT)) +
  geom_point() +
  labs(title = "Relationship Between Annual Generation, Fuel Type, and Income",
       x = "Median Household Income",
       y = "Annual Generation",
       color = "Fuel Type")
print(scatter_income_generation)

#Scatter faceted
scatter_faceted_county <- ggplot(processed_data, aes(x = MEDHHINC_2021, y = PLNGENAN, color = PLFUELCT)) +
  geom_point() +
  facet_wrap(~CNTYNAME, scales = "free") +
  labs(title = "Relationship Between Annual Generation, Fuel Type, and Income by County",
       x = "Median Household Income",
       y = "Annual Generation",
       color = "Fuel Type")
print(scatter_faceted_county)

#Barplot visualization
stacked_barplot_total_generation <- ggplot(processed_data, aes(x = CNTYNAME, y = PLNGENAN, fill = PLFUELCT)) +
  geom_bar(stat = "sum", position = "stack") +
  labs(title = "Total Annual Generation by Fuel Type and County",
       x = "County",
       y = "Total Annual Generation",
       fill = "Fuel Type") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(stacked_barplot_total_generation)

```

```{r}
#Load in counties spatial data
counties_sf<- st_read(here('Data/Spatial/cb_2018_us_county_20m.shp')) %>% 
  filter(STATEFP==37)

#Convert eGrid tabular data to spatial data
plant_gen_sf <-plant_gen_data %>% st_as_sf(coords = c('LON','LAT'), crs=4269)

```


```{r}
#Create initial map of power plants
gens_counties_map <-ggplot()+
  geom_sf(data=counties_sf)+
  geom_sf(data=plant_gen_sf,size=0.8)+
  labs(title = "Locations of NC Power Plants")

gens_counties_map

#Compute sum of nameplate capacity by county
nameplate_capacity <-plant_gen_data %>%
  group_by(CNTYNAME)%>%
  summarize(Sum_NAMEPCAP = sum(NAMEPCAP_plant))

#Join the eGrid attributes to the county spatial features
counties_sf_join <-  merge(x = counties_sf,
                           y = plant_gen_data, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME' )

#Map total generator capacity by county
gen_cap_map <-ggplot(data=counties_sf_join)+
  geom_sf(aes(fill=NAMEPCAP_plant))+labs(title="Generator Capacity by County",fill="Nameplate Capacity")
gen_cap_map

```




```{r Data Wrangling}

#Filter by North Carolina
Plant_NC <- plant %>% filter(PSTATABB=='NC')
gen_NC <-gen %>% filter(PSTATABB=='NC')

#Create Joined Plot
PowerPlants_DF <-merge(x=gen_NC,y=Plant_NC, by='ORISPL',all.x=TRUE)
```

```{r Creating income groupings}

# GENYRRET = Generator planned or actual retirement year (four-digit)
# GENYRONL - year the generator came online (four-digit)

summary(processed_data$GENYRRET) # 1161 NA's
retired_year <- processed_data$GENYRRET %>%
  na.omit()
# earliest year of plant retirement was 2021
# can't run time series analysis with this data, 
# but could run regression analysis to understand relationship between
# planned retirement and 2021 avg household income or
# 2021 retirement and 2021 unemployment
summary(retired_year)

summary(processed_data$GENYRONL) # no NA's
online_plants <- processed_data %>%
  # drop observations with NAs in GENYRONL
  # which means we don't know what year they came online
  # new number of observations should be 1175 (dropping 15 NAs)
  drop_na(GENYRONL) %>%
  select(FIPS_Code, CNTYNAME, SEQGEN, YEAR, PNAME, 
         GENID, GENSTAT, GENYRONL, NAMEPCAP_plant, 
         PLNGENAN, PLCO2AN, COALFLAG, MEDHHINC_2021,	
         Unemployment_rate_2000,	Unemployment_rate_2001,	
         Unemployment_rate_2002,	Unemployment_rate_2003,	
         Unemployment_rate_2004,	Unemployment_rate_2005,	
         Unemployment_rate_2006,	Unemployment_rate_2007,	
         Unemployment_rate_2008,	Unemployment_rate_2009,	
         Unemployment_rate_2010,	Unemployment_rate_2011,	
         Unemployment_rate_2012,	Unemployment_rate_2013,	
         Unemployment_rate_2014,	Unemployment_rate_2015,	
         Unemployment_rate_2016,	Unemployment_rate_2017,	
         Unemployment_rate_2018,	Unemployment_rate_2019,	
         Unemployment_rate_2020,	Unemployment_rate_2021,	
         Unemployment_rate_2022)
summary(online_plants)

online_year <- online_plants$GENYRONL
summary(online_year)

online_month_day_ <- rep(c("01-01-"), length(online_year))

# repeating month_day_ to fill in month and day
# for as many year entries as are found in 
# dropping NAs but may need to keep them in; decide as group
Date_Online <- paste0(online_month_day_,online_year)
summary(Date_Online)
head(Date_Online)
# 1175 observations in Date_Online

# change years to date formats
is.Date(Date_Online) # not a date
Date_Online <- as.Date(Date_Online, format = "%m-%d-%Y")
is.Date(Date_Online) # true

# ensure date column is in date format
online_plants <- online_plants %>%
  mutate(GENYRONL = Date_Online)
is.Date(online_plants$GENYRONL) # true

# identifying the county with the most power plants
county_freq_table <- table(online_plants$CNTYNAME)
view(county_freq_table)
max(county_freq_table) # 48, Robeson County
county_freq_table <- sort(county_freq_table, decreasing = TRUE)
view(county_freq_table)
robeson_online_plants <- online_plants %>%
  filter(CNTYNAME == "Robeson")
unique(robeson_online_plants$PNAME) # 44 unique power plant names
unique(robeson_online_plants$GENID) # 32 unique GENIDs

# multiple regression for just one county, Robeson 
# the one with highest total number of existing plants in 2021
# to understand relationship between year online for each power plant and unemployment 
# need to make table by year
# with 5 columns: Year, FIPS code, number of plants in existence that year, unemployment rate
robeson_year <- year(robeson_online_plants$GENYRONL)
robeson_FIPS_code <- robeson_online_plants$FIPS_Code
## MARKING WHERE GC LEFT OFF
robeson_plant_count <- tally(robeson_online_plants$PNAME, wt = NULL, sort = FALSE, name = NULL)
is.Date(robeson_online_plants$GENYRONL)

## WILL LIKELY NOT NEED 
## INCOME THRESHOLDS FOR TIME SERIES ANALYSIS
# Median Household Income for 2021
summary(processed_data$MEDHHINC_2021)

low_threshold <- 44477
medium_threshold <- 52463

# Create subsets based on income thresholds
low_income_subset <- processed_data[processed_data$MEDHHINC_2021 < low_threshold, ]

medium_income_subset <- processed_data[processed_data$MEDHHINC_2021 >= low_threshold & processed_data$MEDHHINC_2021 < medium_threshold, ]

high_income_subset <- processed_data[processed_data$MEDHHINC_2021 >= medium_threshold, ]

ts_low_income <- ts(low_income_subset$Unemployment_rate_2000:low_income_subset$Unemployment_rate_2022, start = min(low_income_subset$YEAR), end = max(low_income_subset$YEAR))
```


```{r Income and Fuel Category}

################ DATA ANALYSIS: INCOME AND POWER PLANTS ####################

#Regression on Income and the Number of Power Plants

### Pre-Analysis Wrangling ###

# Creating separate df with plants by FIPS_Code
county_plants_table <- table(online_plants$FIPS_Code)
view(county_plants_table)
county_plants_df <- as.data.frame(county_plants_table)

#Renaming columnnames
colnames(county_plants_df)[colnames(county_plants_df) == "Var1"] <- "FIPS_Code"
colnames(county_plants_df)[colnames(county_plants_df) == "Freq"] <- "Num_Plants"
#add in income data
merged_data <- merge(county_plants_df, income[, c("FIPS_Code", "MEDHHINC_2021")], by = "FIPS_Code", all.x = TRUE)
# Merge back to original
county_plants_df <- merged_data

### Regression Analysis ###

#Run simple regression
inc_plants_model <- lm(Num_Plants ~ MEDHHINC_2021, data = county_plants_df)
summary(inc_plants_model)

#Plot relationship
ggplot(county_plants_df, aes(x = MEDHHINC_2021, y = Num_Plants)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Regression Analysis Between Power Plants and County Income",
       x = "Median Household Income",
       y = "Number of Power Plants")

#Regression on Income and Nameplate Capacity

## Pre-Analysis Wrangling ##

#Calculate average nameplate capacity by county
average_capacity <- aggregate(NAMEPCAP_plant ~ FIPS_Code, data = online_plants, FUN = mean)
merged_data_capacity <- merge(average_capacity, income, by = "FIPS_Code")

## Regression Analysis ##

#Run simple regression
capacity_income_model <- lm(NAMEPCAP_plant ~ MEDHHINC_2021, data = merged_data_capacity)

#Plot relationship
ggplot(merged_data_capacity, aes(x = MEDHHINC_2021, y = NAMEPCAP_plant)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Regression Analysis Between Nameplate Capacity and County Income",
       x = "Median Household Income",
       y = "Average Nameplate Capacity")

#Regression on Income and Average Generation

## Pre-Analysis Wrangling ##

#Calculate average generation by county
avg_generation <- aggregate(PLNGENAN ~ FIPS_Code, data = online_plants, FUN = mean)
merged_data_generation <- merge(avg_generation, income, by = "FIPS_Code")

## Regression Analysis ##

#Run simple regression
generation_income_model <- lm(PLNGENAN ~ MEDHHINC_2021, data = merged_data_generation)
summary(generation_income_model)

#Plot relationship
ggplot(merged_data_generation, aes(x = MEDHHINC_2021, y = PLNGENAN)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Regression Analysis Between Average Generation and County Income",
       x = "Median Household Income",
       y = "Total Annual Generation")



```


```{r Generation and SVI Relationship Analysis}
Generation_SVI <-merge(x = avg_generation,
                           y = SVI, 
                           by.x = 'FIPS_Code', 
                           by.y = 'FIPS' )

Generation_County_lm <- lm(PLNGENAN ~ RPL_THEMES + RPL_THEME1 + RPL_THEME2 + RPL_THEME3 + RPL_THEME4, data=Generation_SVI)
summary(Generation_County_lm) 

census_tracts_sf<- st_read(here('Data/Spatial/tl_2021_37_tract.shp'))
```


```{r Heat Maps}
#Heat map of Income Data by County
#Create data frame of NC income data
income_NC <-income %>% 
  filter(Stabr=='NC')

#Join the income attributes to the county spatial features
income_NC_sf_join <-  merge(x = counties_sf,
                           y = income_NC, 
                           by.x = 'GEOID', 
                           by.y = 'FIPS_Code')

#Map pct in poverty by county
income_heat_map <-ggplot(data=income_NC_sf_join)+
  geom_sf(aes(fill=PCTPOV017_2021))+labs(title= "% of County in Poverty - 2021", fill="%")
income_heat_map

#Heat map of CO2 emissions by county
#Compute sum of CO2 Emissions by county
CO2_emissions <-plant_gen_data %>%
  drop_na(PLCO2AN)%>%
  group_by(CNTYNAME)%>%
  summarize(Sum_CO2 = sum(PLCO2AN))

#Join the eGrid attributes to the county spatial features
CO2_counties_sf_join <-  merge(x = counties_sf,
                           y = CO2_emissions, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME')

#Map CO2 emissions by county
CO2_map <-ggplot(data=CO2_counties_sf_join)+
  geom_sf(aes(fill=Sum_CO2))+
  labs(title="2021 CO2 Emissions",
       fill="CO2 Emissions (tn)")
CO2_map

#Heat map of NOx emissions by county
#Compute sum of NOx Emissions by county
NOx_emissions <-plant_gen_data %>%
  drop_na(PLNOXAN)%>%
  group_by(CNTYNAME)%>%
  summarize(Sum_NOx = sum(PLNOXAN))

#Join the eGrid attributes to the county spatial features
NOx_counties_sf_join <-  merge(x = counties_sf,
                           y = NOx_emissions, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME')

#Map NOx emissions by county
NOx_map <-ggplot(data= NOx_counties_sf_join)+
  geom_sf(aes(fill=Sum_NOx))+
  labs(title="2021 NOx Emissions",
       fill=" NOx Emissions (tn)")
NOx_map

#Heat map of SO2 emissions by county
#Compute sum of SO2 Emissions by county
SO2_emissions <-plant_gen_data %>%
  drop_na(PLSO2AN)%>%
  group_by(CNTYNAME)%>%
  summarize(Sum_SO2 = sum(PLSO2AN))

#Join the eGrid attributes to the county spatial features
SO2_counties_sf_join <-  merge(x = counties_sf,
                           y = SO2_emissions, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME')

#Map SO2 emissions by county
SO2_map <-ggplot(data=SO2_counties_sf_join)+
  geom_sf(aes(fill=Sum_SO2))+
  labs(title="2021 SO2 Emissions",
       fill="SO2 Emissions (tn)")
SO2_map

#Heat map of N2O emissions by county
#Compute sum of N2O Emissions by county
N2O_emissions <-plant_gen_data %>%
  drop_na(PLN2OAN)%>%
  group_by(CNTYNAME)%>%
  summarize(Sum_N2O = sum(PLN2OAN))

#Join the eGrid attributes to the county spatial features
N2O_counties_sf_join <- merge(x = counties_sf,
                           y = N2O_emissions, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME')

#Map N2O emissions by county
N2O_map <-ggplot(data= N2O_counties_sf_join)+
  geom_sf(aes(fill=Sum_N2O))+
  labs(title="2021 N2O Emissions",
       fill=" N2O Emissions (lbs)")
N2O_map


#Heat map of CH4 emissions by county
#Compute sum of CH4 Emissions by county
CH4_emissions <-plant_gen_data %>%
  drop_na(PLCH4AN)%>%
  group_by(CNTYNAME)%>%
  summarize(Sum_CH4 = sum(PLCH4AN))

#Join the eGrid attributes to the county spatial features
CH4_counties_sf_join <- merge(x = counties_sf,
                           y = CH4_emissions, 
                           by.x = 'NAME', 
                           by.y = 'CNTYNAME')

#Map CH4 emissions by county
CH4_map <-ggplot(data= CH4_counties_sf_join)+
  geom_sf(aes(fill=Sum_CH4))+
  labs(title="2021 CH4 Emissions",
       fill="CH4 Emissions (lbs)")
CH4_map

```


```{r Unemployment and Retirements}

################ DATA ANALYSIS: UNEMPLOYMENT AND GENERATOR RETIREMENTS ################ 

### Pre-Analysis Wrangling ###

#Set to numeric
gen20$NAMEPCAP <- as.numeric(gen20$NAMEPCAP)
gen20$GENNTOZ <- as.numeric(gen20$GENNTOZ)

summary(gen20)

#Combining gen20 and plant dataframes based on ORISPL
plant_gen20 <- gen20 %>%
  inner_join(plant_select, by = 'ORISPL', 
             suffix = c("_gen", "_plant"))

#Removing duplicate state abbreviation column
plant_gen_data_20 <- plant_gen20[, -which(names(plant_gen) == "PSTATABB_plant")]

#Merging with eGrid
ue_egrid_20 <- merge(plant_gen_data_20, ue, by = "FIPS_Code")

#Merging with income
processed_data_20 <- merge(ue_egrid_20, inc, by = "FIPS_Code")

#View existing column names to explore next steps
colnames(processed_data_20)
colnames(ue)

#Transposing and wrangling both in order to view:
#   1. NC county unemployment by year, where we have a column for all years rather than each year having its own column
#   2. Generator retirement by year, selecting only those with instances of retired generators

#Unemployment
transposed_ue <- ue %>%
  filter(str_starts(FIPS_Code, "37")) %>%  # Filter to include only NC
  pivot_longer(cols = starts_with("Unemployment_rate_"), 
               names_to = "Year", 
               values_to = "Unemployment") %>%
  mutate(Year = gsub("Unemployment_rate_", "", Year, fixed = TRUE)) %>%
  pivot_wider(names_from = "FIPS_Code", values_from = "Unemployment")

#Generator
generator_retirement_data <- processed_data_20 %>% 
  select(FIPS_Code, GENYRRET) %>%
  na.omit()  #showing only generators that have retired


###### EXPLORATION #######

#Use table to count the occurrences of each unique FIPS code to select counties of interest
fips_counts <- table(generator_retirement_data$FIPS_Code)

for (i in seq_along(fips_counts)) {
  fips <- names(fips_counts)[i]
  count <- fips_counts[i]
  cat("FIPS Code:", fips, "has", count, "rows.\n")}

fips_counts <- table(generator_retirement_data$FIPS_Code)#identifies 2 counties with 7 instances of retirements


#FIPS Code 37159 (Rowan) and 37191 (Wayne) each have 7 rows: use these as counties of interest to run time series
#FIPS Code 37023  (Burke) 37041 (Chowan) 37049  (Craven) 37063 (Durham) 37067 (Forsyth) 37069 (Franklin) 37125 (Moore) each have 1 row: use these as counties of interest for comparison


colnames(transposed_ue)

#Creating df for only columns.counties of interest
rowan_ue <- transposed_ue[, c("Year", "37159")]
wayne_ue <- transposed_ue[, c("Year", "37191")]
durham_ue <- transposed_ue[, c("Year", "37063")] 
Chowan_ue <- transposed_ue[, c("Year", "37049")] 

rowan_ret <-  generator_retirement_data[generator_retirement_data$FIPS_Code == 37159, ]
wayne_ret <-  generator_retirement_data[generator_retirement_data$FIPS_Code == 37191, ]
durham_ret <-  generator_retirement_data[generator_retirement_data$FIPS_Code == 37063, ]
Chowan_ret <-  generator_retirement_data[generator_retirement_data$FIPS_Code == 37049, ]


#Converting to date format
rowan_ue$Year <- as.Date(rowan_ue$Year, format = "%Y")
wayne_ue$Year <- as.Date(wayne_ue$Year, format = "%Y")
durham_ue$Year <- as.Date(durham_ue$Year, format = "%Y")
Chowan_ue$Year <- as.Date(durham_ue$Year, format = "%Y")

#Plot
ggplot(rowan_ue, aes(x = Year, y = `37159`)) +
  geom_point(color = "blue") +
  labs(title = "Unemployment in Rowan County",
       x = "Year",
       y = "Unemployment Rate (%)")

# Line plot for Rowan and Wayne
ggplot() +
  geom_line(data = rowan_ue, aes(x = Year, y = `37159`, color = "Rowan"), size = 1) +
  geom_line(data = wayne_ue, aes(x = Year, y = `37191`, color = "Wayne"), size = 1) +
  labs(title = "Unemployment in Wayne and Rowan Counties",
       x = "Year",
       y = "Unemployment Rate (%)",
       color = "Dataset") +
  scale_color_manual(values = c("Rowan" = "blue", "Wayne" = "lightblue")) +
  theme(legend.title = element_blank())  

combined_plot <- ggplot() +
  geom_line(data = rowan_ue, aes(x = Year, y = `37159`, color = "Rowan"), size = 1) +
  geom_line(data = wayne_ue, aes(x = Year, y = `37191`, color = "Wayne"), size = 1) +
  geom_line(data = durham_ue, aes(x = Year, y = `37063`, color = "Durham"), size = 1) +
  geom_line(data = Chowan_ue, aes(x = Year, y = `37049`, color = "Chowan"), size = 1) +
  geom_vline(xintercept = 2012, linetype = "dashed", color = "black", size = 1) +
  labs(title = "Unemployment in Wayne, Rowan, Durham, and Chowan Counties",
       x = "Year",
       y = "Unemployment Rate (%)",
       color = "Dataset") +
  scale_color_manual(values = c("Rowan" = "blue", "Wayne" = "lightblue", "Durham" = "darkgreen", "Chowan" = "lightgreen")) +
  theme(legend.title = element_blank())

print(combined_plot)


# Add dashed line at year 2012 with legend
combined_plot + 
  geom_vline(xintercept = 2012, linetype = "dashed", color = "black", size = 1) +
  labs(color = "Legend Title")


#Selecting Rowan only
rowan_data <- generator_retirement_data[generator_retirement_data$FIPS_Code == 37159, ]

#Rename generator retirement year to year in order to combine for analysis
colnames(rowan_data)[colnames(rowan_data) == "GENYRRET"] <- "Year"

#Merge by year
rowan_merged_data <- merge(rowan_data, rowan_ue, by = "Year", all.x = TRUE)


#Plot does not suggest further analysis. Instead of instances of retirements, moving forward with comparing the impact of the total retired nameplate with unemployment

### Data Wrangling ###

#Renaming columnn
names(rowan_ue)[trimws(names(rowan_ue)) == "37159"] <- "Rowan UE (%)"

#Adding nameplate capacity to generator
rowan_generator_retirement_NPACP <- processed_data_20 %>% 
  select(FIPS_Code, GENYRRET, NAMEPCAP_gen) %>%
  filter(FIPS_Code == "37159") %>%  # Filter for Rowan county
  na.omit() %>% #selecting only data with retirements
  rename(Year = GENYRRET)  # Renaming the column

#Converting to date format
rowan_generator_retirement_NPACP$Year <- as.Date(paste(rowan_generator_retirement_NPACP$Year, "12-06", sep = "-"), format = "%Y-%m-%d")


#Merging
rowan_merged_data_NPCAP <- merge(rowan_generator_retirement_NPACP, rowan_ue, by = "Year", all.x = TRUE)


#### Data Analysis ###

#Linear regression
lm_result <- lm(`Rowan UE (%)` ~ NAMEPCAP_gen, data = rowan_merged_data_NPCAP)
summary(lm_result) 

#Contrary to the initial hypothesis, this regression indicates that for each MW increase in retired nameplate capacity, the unemployment rate unemployment rate in Rowan is expected to decrease by approximately 0.02428 percentage points. The p-value is greater than 0.05,but given that it is only marginally higher (at 0.0619) we can theoretically interpret there to be a weak relationship. However, it must be understood that the sample size is small and therefore we would need much more data for any reliable conclusions.

#The Multiple R-squared value of 0.5346 represents the proportion of the variance in the response variable (Rowan UE (%)) that can be explained by the predictor variable retired nameplate capacity (MW).

# Visualize the relationship
ggplot(rowan_merged_data_NPCAP, aes(x = NAMEPCAP_gen, y = `Rowan UE (%)`)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Relationship between Retired Nameplate Capacity and Unemployment Rate",
       x = "Retired Nameplate Capacity (MW)",
       y = "Unemployment Rate (%)")

#Evaluate correlation
cor_test_result <- cor.test(rowan_merged_data_NPCAP$`Rowan UE (%)`, rowan_merged_data_NPCAP$NAMEPCAP_gen)
print(cor_test_result)

#A correlation coefficient of -0.731 suggests that as the retired nameplate capacity (MW) increases, the unemployment rate tends to decrease, contrary to our initial hypothesis. 

```



